name: Events Demo 1
on:
  pull_request:
    types:
      - opened
    branches:
      - "main" # pull_request targets main branch
      - "dev-*" # pull_request targets eg dev-lp branch
      - "feat/**" # pull_request targets eg feat/hello/world branch
  push:
    branches:
      - "main" # pull_request targets main branch
      - "dev-*" # pull_request targets eg dev-lp branch
      - "feat/**" # pull_request targets eg feat/hello/world branch
    paths-ignore:
      - ".github/workflows/**"
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm ci
      - name: Test code
        run: npm run test
      - name: Build code
        run: npm run build
      - name: Deploy project
        run: echo "Deploying..." 